/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mariokart;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author tonyi
 */
public class JFrameMain extends javax.swing.JFrame {
    Coche cocheRojo;
    Coche cocheVerde;
    Coche cocheAzul;
    Coche cocheAmarillo; 
    GestorFondo gestor;
    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() throws InterruptedException {
        this.setLocationRelativeTo(null);
        initComponents();
        
        cocheRojo = new Coche(jProgressCocheRojo, "rojo");
        Thread thread1 = new Thread(cocheRojo);
        thread1.start();
        
        cocheVerde = new Coche(jProgressCocheVerde, "verde");
        Thread thread2 = new Thread(cocheVerde);
        thread2.start();
        
        cocheAzul = new Coche(jProgressCocheAmarillo, "amarillo");
        Thread thread3 = new Thread(cocheAzul);
        thread3.start();
        
        cocheAmarillo = new Coche(jProgressCocheAzul, "azul");
        Thread thread4 = new Thread(cocheAmarillo);
        thread4.start();
        
        gestor = new GestorFondo(mainPanel);
        Thread thread5 = new Thread(gestor);
        thread5.start();
        /*
        thread1.join();
        thread2.join();
        thread2.join();
        thread4.join();
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jProgressCocheVerde = new javax.swing.JProgressBar();
        jProgressCocheAzul = new javax.swing.JProgressBar();
        jButtonDetenerCocheAzul = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jProgressCocheAmarillo = new javax.swing.JProgressBar();
        jProgressCocheRojo = new javax.swing.JProgressBar();
        jButtonDetenerCocheVerde = new javax.swing.JButton();
        jButtonDetenerCocheRojo = new javax.swing.JButton();
        jButtonDetenerCocheAmarillo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelVerde = new javax.swing.JLabel();
        jLabelAmarillo = new javax.swing.JLabel();
        jLabelAzul = new javax.swing.JLabel();
        jLabelRojo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jProgressCocheVerde.setForeground(new java.awt.Color(0, 204, 0));

        jProgressCocheAzul.setForeground(new java.awt.Color(102, 204, 255));

        jButtonDetenerCocheAzul.setText("Stop");
        jButtonDetenerCocheAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetenerCocheAzulActionPerformed(evt);
            }
        });

        jButton3.setText("Detener fondo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jProgressCocheAmarillo.setForeground(new java.awt.Color(255, 255, 102));

        jProgressCocheRojo.setForeground(new java.awt.Color(255, 102, 102));

        jButtonDetenerCocheVerde.setText("Stop");
        jButtonDetenerCocheVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetenerCocheVerdeActionPerformed(evt);
            }
        });

        jButtonDetenerCocheRojo.setText("Stop");
        jButtonDetenerCocheRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetenerCocheRojoActionPerformed(evt);
            }
        });

        jButtonDetenerCocheAmarillo.setText("Stop");
        jButtonDetenerCocheAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetenerCocheAmarilloActionPerformed(evt);
            }
        });

        jButton1.setText("Caparazon azul");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Caparazon rojo");

        jLabel1.setText("PUESTO");

        jLabelVerde.setText("Verde");

        jLabelAmarillo.setText("Amarillo");

        jLabelAzul.setText("Azul");

        jLabelRojo.setText("Rojo");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(27, 27, 27)
                .addComponent(jButton2)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelVerde)
                            .addComponent(jLabelAmarillo)
                            .addComponent(jLabelAzul)
                            .addComponent(jLabelRojo))
                        .addGap(24, 24, 24)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressCocheVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressCocheRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressCocheAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressCocheAmarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonDetenerCocheAzul)
                            .addComponent(jButtonDetenerCocheVerde)
                            .addComponent(jButtonDetenerCocheAmarillo)
                            .addComponent(jButtonDetenerCocheRojo)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressCocheVerde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelVerde, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDetenerCocheVerde)))
                .addGap(9, 9, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonDetenerCocheAzul)
                    .addComponent(jProgressCocheAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAzul))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(jProgressCocheAmarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(jLabelAmarillo)
                                .addGap(5, 5, 5)))
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jProgressCocheRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRojo)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jButtonDetenerCocheAmarillo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDetenerCocheRojo)))
                .addGap(28, 28, 28)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDetenerCocheAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetenerCocheAzulActionPerformed
            cocheAzul.detenerCoche();
    }//GEN-LAST:event_jButtonDetenerCocheAzulActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        gestor.running = false;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonDetenerCocheVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetenerCocheVerdeActionPerformed
        // TODO add your handling code here:
        cocheVerde.detenerCoche();
    }//GEN-LAST:event_jButtonDetenerCocheVerdeActionPerformed

    private void jButtonDetenerCocheRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetenerCocheRojoActionPerformed
        // TODO add your handling code here:
        cocheRojo.detenerCoche();
    }//GEN-LAST:event_jButtonDetenerCocheRojoActionPerformed

    private void jButtonDetenerCocheAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetenerCocheAmarilloActionPerformed
        // TODO add your handling code here:
        cocheAmarillo.detenerCoche();
    }//GEN-LAST:event_jButtonDetenerCocheAmarilloActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFrameMain().setVisible(true);
                } catch (InterruptedException ex) {
                    Logger.getLogger(JFrameMain.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }
    public static void colocarPuesto(String color, String puesto) {
        switch (color) {
            case "verde": jLabelVerde.setText(puesto);
                break;
                
            case "azul": jLabelAzul.setText(puesto);
                break;
            
            case "amarillo": jLabelAmarillo.setText(puesto);
                break;
            
            case "rojo": jLabelRojo.setText(puesto);
                break;
            
            default:
                throw new AssertionError();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonDetenerCocheAmarillo;
    private javax.swing.JButton jButtonDetenerCocheAzul;
    private javax.swing.JButton jButtonDetenerCocheRojo;
    private javax.swing.JButton jButtonDetenerCocheVerde;
    private javax.swing.JLabel jLabel1;
    private static javax.swing.JLabel jLabelAmarillo;
    private static javax.swing.JLabel jLabelAzul;
    private static javax.swing.JLabel jLabelRojo;
    private static javax.swing.JLabel jLabelVerde;
    private javax.swing.JProgressBar jProgressCocheAmarillo;
    private javax.swing.JProgressBar jProgressCocheAzul;
    private javax.swing.JProgressBar jProgressCocheRojo;
    private javax.swing.JProgressBar jProgressCocheVerde;
    private static javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
